# Site settings
title: zylajeff # site title
description: Jeff's Musings
lang: en-US # default lang
timezone: US/EDT # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: 
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Jeff Zyla # author name
  bio: >
        Engineering Team Leader @ Amazon <br />
        Self proclaimed ambassador for Detroit <br />
        Spartan <br />
        Tinkerer <br />
  username: zylajeff # social media username eg. github, twitter 
  email: zyla.jeff@gmail.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: "https://klise.now.sh"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
